# Generated by Django 5.2.4 on 2025-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_quests/%Y/%m/%d/'),
        ),
    ]
