# Generated by Django 5.2.4 on 2025-08-20 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_quest_created_by_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
